In [30]:
import pandas as pd

df =  pd.read_csv('data/sept20todec2021.csv')

df

,Sale Date,Add Date,Case Number,Status,Final Judgment,Opening Bid,Assessed Value,Primary Plaintiff,Certificate Holder Name,Plaintiff Max Bid,Address,City,Zip,Parcel ID,My Bid
0,09/20/2021,06/14/2021,292018CA005366A001HC,Accepting Proxy,128356.39,0,133261,NATIONSTAR MORTGAGE LLC,NATIONSTAR MORTGAGE LLC,HIDDEN,1601 N ORANGE ST,PLANT CITY,33563.0,2228205B3000002000010P,NaN
1,09/20/2021,07/23/2021,292019CA013040A001HC,Accepting Proxy,151815.40,0,84434,U.S. BANK NATIONAL ASSOCIATION,U.S. BANK NATIONAL ASSOCIATION,HIDDEN,4304 CORONET RD,PLANT CITY,33566.0,222902ZZZ000004832000U,NaN
2,09/20/2021,08/16/2021,292018CA010101A001HC,Accepting Proxy,253987.70,0,203998,HOMEBRIDGE FINANCIAL SERVICES INC,HOMEBRIDGE FINANCIAL SERVICES INC,HIDDEN,10307 ASHLEY OAKS DR,RIVERVIEW,33578.0,2030172RB000004000380U,NaN
3,09/20/2021,09/01/2021,292020CA009864A001HC,Accepting Proxy,180560.79,0,99934,U.S. BANK TRUST NATIONAL ASSOCIATION AS TRUSTE...,U.S. BANK TRUST NATIONAL ASSOCIATION AS TRUSTE...,180560.79,7018 PONDEROSA DR,TAMPA,33637.0,1928231IQ000009000070U,NaN
4,09/21/2021,07/21/2021,292014CA001244A001HC,Accepting Proxy,399041.46,0,218717,US BANK NA,US BANK NA,HIDDEN,4950 BAYSHORE BLVD 31,TAMPA,33611.0,18301140A000000000310A,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,11/24/2021,07/27/2021,292020CA002259A001HC,Accepting Proxy,0.00,0,0,US BANK TRUST NATIONAL ASSOCIATION,US BANK TRUST NATIONAL ASSOCIATION,HIDDEN,NaN,NaN,NaN,NaN,NaN
140,11/24/2021,09/01/2021,292020CA009314A001HC,Accepting Proxy,0.00,0,0,"Wilmington Savings Fund Society, FSB","Wilmington Savings Fund Society, FSB",HIDDEN,NaN,NaN,NaN,NaN,NaN
141,12/02/2021,08/24/2021,292020CA002247A001HC,Accepting Proxy,0.00,0,0,REGIONS BANK,REGIONS BANK,HIDDEN,NaN,NaN,NaN,NaN,NaN
142,12/07/2021,08/11/2021,292018CA003822A001HC,Accepting Proxy,0.00,0,0,"U.S. Bank, NA","U.S. Bank, NA",HIDDEN,NaN,NaN,NaN,NaN,NaN
143,12/09/2021,07/14/2021,292018CA009441A001HC,Accepting Proxy,0.00,0,0,NATIONSTAR MORTGAGE LLC,NATIONSTAR MORTGAGE LLC,HIDDEN,NaN,NaN,NaN,NaN,NaN

In [31]:
to_drop = ['Status', 
          'Opening Bid',
           'Primary Plaintiff',
           'Certificate Holder Name',
           'Plaintiff Max Bid',
          'My Bid',
          ]

In [32]:
df.drop(columns=to_drop, inplace=True)

In [33]:
df

,Sale Date,Add Date,Case Number,Final Judgment,Assessed Value,Address,City,Zip,Parcel ID
0,09/20/2021,06/14/2021,292018CA005366A001HC,128356.39,133261,1601 N ORANGE ST,PLANT CITY,33563.0,2228205B3000002000010P
1,09/20/2021,07/23/2021,292019CA013040A001HC,151815.40,84434,4304 CORONET RD,PLANT CITY,33566.0,222902ZZZ000004832000U
2,09/20/2021,08/16/2021,292018CA010101A001HC,253987.70,203998,10307 ASHLEY OAKS DR,RIVERVIEW,33578.0,2030172RB000004000380U
3,09/20/2021,09/01/2021,292020CA009864A001HC,180560.79,99934,7018 PONDEROSA DR,TAMPA,33637.0,1928231IQ000009000070U
4,09/21/2021,07/21/2021,292014CA001244A001HC,399041.46,218717,4950 BAYSHORE BLVD 31,TAMPA,33611.0,18301140A000000000310A
...,...,...,...,...,...,...,...,...,...
139,11/24/2021,07/27/2021,292020CA002259A001HC,0.00,0,NaN,NaN,NaN,NaN
140,11/24/2021,09/01/2021,292020CA009314A001HC,0.00,0,NaN,NaN,NaN,NaN
141,12/02/2021,08/24/2021,292020CA002247A001HC,0.00,0,NaN,NaN,NaN,NaN
142,12/07/2021,08/11/2021,292018CA003822A001HC,0.00,0,NaN,NaN,NaN,NaN
143,12/09/2021,07/14/2021,292018CA009441A001HC,0.00,0,NaN,NaN,NaN,NaN